language: java

# Work around travis-ci/travis-ci/issues/6593
sudo: true
cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk8

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
  - mvn --settings .travis/settings.xml clean install -P checkerframework
  - cd gradle-plugin; ./gradlew build --scan -s
  - cd camunda-modeler-plugin; npm install; npm run bundle; cd -

after_success:
  - mvn clean test jacoco:report coveralls:report

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: red6/dmn-check
      tags: true
      jdk: openjdk8

  -
    provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: red6/dmn-check
      branch: master
      jdk: openjdk8
